package ihm;


import java.net.URL;
import partie.Partie;



/**
 *
 * @author Arnaud
 */
public class PanelBoutons extends javax.swing.JPanel {
    private Partie partie;
    private URL urlBase;
    

    /**
     * Creates new form PanelBoutons
     */
    public PanelBoutons() {
        partie = new Partie();
        urlBase = getClass().getResource("/ressources/");
        initComponents();
    }
    
    public Partie getPartie() {
        return partie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boutonCC = new javax.swing.JButton();
        boutonCD = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        boutonDC = new javax.swing.JButton();
        boutonDD = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Prochaine action : "));
        setMaximumSize(null);
        setMinimumSize(null);
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Joueur A / Joueur B");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Coopère");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Fait Défaut");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel3, gridBagConstraints);

        jLabel4.setText("Coopère");
        add(jLabel4, new java.awt.GridBagConstraints());

        boutonCC.setText("<html><img src='" + urlBase + "/ok.png'/><img src='" + urlBase + "/ok.png'/></html>");
        boutonCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(boutonCC, gridBagConstraints);

        boutonCD.setText("<html><img src='" + urlBase + "/ok.png'/><img src='" + urlBase + "/non.png'/></html>");
        boutonCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(boutonCD, gridBagConstraints);

        jLabel5.setText("Fait Défaut");
        add(jLabel5, new java.awt.GridBagConstraints());

        boutonDC.setText("<html><img src='" + urlBase + "/non.png'/><img src='" + urlBase + "/ok.png'/></html>");
        boutonDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(boutonDC, gridBagConstraints);

        boutonDD.setText("<html><img src='" + urlBase + "/non.png'/><img src='" + urlBase + "/non.png'/></html>");
        boutonDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(boutonDD, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCDActionPerformed
        partie.jouer(true, false);
    }//GEN-LAST:event_boutonCDActionPerformed

    private void boutonCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCCActionPerformed
       partie.jouer(true, true);
    }//GEN-LAST:event_boutonCCActionPerformed

    private void boutonDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDCActionPerformed
       partie.jouer(false, true);
    }//GEN-LAST:event_boutonDCActionPerformed

    private void boutonDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDDActionPerformed
        partie.jouer(false, false);
    }//GEN-LAST:event_boutonDDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonCC;
    private javax.swing.JButton boutonCD;
    private javax.swing.JButton boutonDC;
    private javax.swing.JButton boutonDD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
