/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.Observable;
import java.util.Observer;
import partie.Partie;


/**
 *
 * @author greta
 */
public class PanelSynthese extends javax.swing.JPanel implements Observer {
    private final Partie partie;
    private int scoreA, scoreB;

    /**
     * Creates new form PanelSynthese
     */
    public PanelSynthese(Partie unePartie) {
        partie = unePartie;
        partie.addObserver(this);
        scoreA = 0;
        scoreB = 0;
        initComponents();
    }
    
    public PanelSynthese() {
        this(new Partie());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        labelNbCoup = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelScoreA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelScoreB = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Synthèse : "));
        setMaximumSize(new java.awt.Dimension(200, 95));
        setMinimumSize(new java.awt.Dimension(200, 95));
        setPreferredSize(new java.awt.Dimension(200, 95));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombre de Tours : ");
        add(jLabel1, new java.awt.GridBagConstraints());

        labelNbCoup.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(labelNbCoup, gridBagConstraints);

        jLabel3.setText("Score A :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel3, gridBagConstraints);

        labelScoreA.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(labelScoreA, gridBagConstraints);

        jLabel5.setText("Score B :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel5, gridBagConstraints);

        labelScoreB.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(labelScoreB, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelNbCoup;
    private javax.swing.JLabel labelScoreA;
    private javax.swing.JLabel labelScoreB;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        labelNbCoup.setText("" + partie.getNbTours());
        scoreA += partie.getTours().get(partie.getNbTours()-1).getGainA();
        scoreB += partie.getTours().get(partie.getNbTours()-1).getGainB();
        labelScoreA.setText("" + scoreA);
        labelScoreB.setText("" + scoreB);
    }
}
